pip3 install https://github.com/New-dev0/Telethon/archive/platy.zip
pip3 install python-decouple
pip3 install python-dotenv
pip3 install akinator
pip3 install apscheduler
pip3 install aiohttp
pip3 install bs4
pip3 install enhancer
pip3 install git+https://github.com/New-dev0/instagrapi.git@39df1b1#egg=instagrapi
pip3 install git+https://github.com/buddhhu/img2html.git@c44170d#egg=img2html
pip3 install heroku3
pip3 install coloredlogs
pip3 install gitpython
pip3 install google-api-python-client
pip3 install htmlwebshot
pip3 install lottie
pip3 install lxml
pip3 install numpy
pip3 install oauth2client
pip3 install opencv-python-headless
pip3 install pillow
pip3 install profanitydetector
pip3 install psutil
pip3 install pypdf2
pip3 install pytz
pip3 install qrcode
pip3 install requests
pip3 install tabulate
pip3 install git+https://github.com/xditya/telegraph.git@41fd800#egg=telegraph
pip3 install tgcrypto
pip3 install youtube-search-python
pip3 install yt-dlp
